### ISSUE TITLE
Expose the parser

### ISSUE THREAD

**Issue by DebugSteven** [nikita-volkov/hasql-th#1]
Would it be possible to separate the reimplementation of the Postgres SQL syntax parser out as its own module? It could be really useful to have it available for any library that wants to have raw SQL queries.

**Comment by nikita-volkov** [comment]
It would require some factoring work, but it's doable. I'll postpone it until someone comes with a specific request.

**Comment by 3noch** [comment]
I was just about to request the same thing. While hasql is awesome, your parser might be even more awesome. :wink:

**Comment by 3noch** [comment]
I personally would love to integrate it with `postgresql-simple` if it were available.

**Comment by nikita-volkov** [comment]
It seems like it's becoming a popular request. I'll factor the syntactical stuff out to my previously abandoned "postgresql-syntax" project once I get the time.

**Comment by DebugSteven** [comment]
I have some time to try refactoring the parser out. If I get it working I'll put up a PR here (or against postgresql-syntax if that makes more sense).

**Comment by lrworth** [comment]
I really want to leverage this to make an SQL auto-formatter.

**Comment by lrworth** [comment]
Any progress @DebugSteven or @nikita-volkov?

I might have a bit of time to do this myself now.

**Comment by nikita-volkov** [comment]
I'll do this in the coming days. The problem is that I need to isolate the generic parts from what is required only for the purposes of "hasql-th".

**Comment by dredozubov** [comment]
I would really appreciate this being done, love the library!

**Comment by nikita-volkov** [comment]
It's done. See http://hackage.haskell.org/package/postgresql-syntax

**Comment by 3noch** [comment]
Awesome!
