### ISSUE TITLE
Possibility to splice table names?

### ISSUE THREAD

**Issue by Javran** [nikita-volkov/hasql-th#13]
Well, sorry I clicked post button way too early....

so basically I'm wondering if the following is possible:

```haskell
queryStatement :: Text -> Statement (Vector Int64) (Vector Int64)
queryStatement tableName =
    [vectorStatement|SELECT foo :: int8 FROM ${encodeUtf8 tableName}|]
```
for now it complains about:

```
 unexpected "${tableName}"
 expecting table reference or white space
```

the error sounds like I've got the unquote syntax wrong though...

**Comment by nikita-volkov** [comment]
This is not supported and likely never will be since it's not the purpose of this library.
