### ISSUE TITLE
invalid UPSERT syntax parsed successfully

### ISSUE THREAD

**Issue by wfranzini** [nikita-volkov/hasql-th#15]
hasql-th 0.4.0.4, I've not seen related commits in more recent releases,  accept incorrect INSERT with ON CONFLICT statements (UPSERT).

In the ON CONFLICT clause the conflict_target is mandatory, unless the action is DO NOTHING. This is, however, stated in the explanation of the clause [ON CONFLICT](https://www.postgresql.org/docs/9.5/sql-insert.html#SQL-ON-CONFLICT ) and not in the synopsis.

As an example the query in the log fragment has been accepted by hasql-th but refused by PostgreSQL 11:
```
STATEMENT:  INSERT INTO ad_user (dn) VALUES ($1 :: text) ON CONFLICT DO UPDATE SET dn = ad_user.dn RETURNING id :: int4
ERROR:  ON CONFLICT DO UPDATE requires inference specification or constraint name at character 46
HINT:  For example, ON CONFLICT (column_name).
```

**Comment by nikita-volkov** [comment]
After parsing a syntax tree Postgresql performs analysis on it at the next stage, validating such cases as in your case. The error that you get from Postgres originates from analyser, not parser. Hasql-th however only implements the parser, which is enough for its purposes.
