### ISSUE TITLE
Column casting with "::": is it possible?

### ISSUE THREAD

**Issue by hugodro** [nikita-volkov/hasql-th#16]
I'm trying to transpose some SQL queries from psql scripts into Hasql-TH with a minimum of modifications, and I got stuck getting compile errors on a "tpath::varchar" expression.  The following is (impressively) almost working directly, but breaks on the tpath cast on the last line:
```
selectStmt = [TH.vectorStatement|
  with recursive pathup as (
    select label, id, parentid, label || ';' as tpath, 1 as depth
      from taxonode
      where id = $1::int4
    union all
     select nd.label, nd.id, nd.parentid, nd.label || '/' || pu.tpath as tpath, pu.depth+1 as depth
       from taxonode as nd
        inner join pathup pu on pu.parentid = nd.id
  ) select tpath::varchar::text, id::int4, depth::int4 from pathup order by depth desc
  |]

```
I solved the problem by rewriting as "cast(tpath as varchar)::text" but I'd prefer to use the typical "::<sql-type>" of Postgresql.  Is there something in Hasql-TH to make the "::" conversions part of the SQL syntax rather than the Haskell one?

**Comment by nikita-volkov** [comment]
Have you tried the latest release? Your statement parses fine with it

**Comment by hugodro** [comment]
So simple... (I just updated to 0.4.0.8)!  Thanks for the quick reply!!
