### ISSUE TITLE
How to template hasql-th?

### ISSUE THREAD

**Issue by domenkozar** [nikita-volkov/hasql-th#17]
I'd like to define all columns for a table in a single place, then reference that in each query.

Is there currently a way to do so?

**Comment by nikita-volkov** [comment]
I don't think so. But I may be misunderstanding. Can you clear this out?

**Comment by domenkozar** [comment]
I'd like to use string interpolation. 

So that I can define pieces of queries and glue them together with strings, then at the end syntax is checked by hasql-th.

**Comment by domenkozar** [comment]
Seems similar to https://github.com/nikita-volkov/hasql-th/issues/13

**Comment by nikita-volkov** [comment]
You can build something around the postgresql-syntax library using hasql-th as a reference

**Comment by domenkozar** [comment]
A good example is also `LIMIT { number | ALL }]`, how does one represent that with hasql-th? Is there something built-in?

**Comment by nikita-volkov** [comment]
Right now hasql-th only supports static parametric queries. What you're looking for is dynamic queries. The closest thing I can suggest is the hasql-dynamic-statements package (but there'll be no syntax checking).

**Comment by domenkozar** [comment]
I don't think they are really dynamic. 

At most there's a boolean condition if some extra filtering should be preformed.

I don't mind if I hasql-th has to compile all possible combinations statically I need as there wouldn't be more than let's say 1-3 booleans.

This would mean it only needs to support something like `AbstractStatement` that wouldn't get syntax checked until it is formatted into `Statement` via TH.

**Comment by nikita-volkov** [comment]
Actually the `limit` case can be solved parametrically. Providing `null` as the value for `limit` achieves the same as setting `all` or omitting the `limit` clause altogether. E.g.,

![image](https://user-images.githubusercontent.com/1560937/90334986-34cdf980-dfda-11ea-8183-edda05e76f3d.png)

So for this problem you can simply use a nullable encoder for the parameter to `limit`.

**Comment by domenkozar** [comment]
That solves the limit problem, although I usually have CRUD operation where the same things are returned by multiple queries that have to duplicate encoders, so each time the record is modified all those queries have to be fixed.

**Comment by nikita-volkov** [comment]
Could you elaborate?

**Comment by domenkozar** [comment]
A typical example is having an `account` in database. You may have different queries for different purposes, for example:

- listing all users
- getting a particular user
- getting users part of a group
- etc

They all share the same `Account` record that is mapped from the database, but you have to specify those fields for each query currently, making it cumbersome to add new fields to the record.

I think the following would solve it:

- `StatementTemplate` that wouldn't syntax check SQL and it wouldn't have `Statement` instance, but you can only use it to be inserted inside the Statement
- `Statement` would stay as it but allow something like `${myStatementTemplate}` to be placed inside 

Ideally `StatementTemplate` could include other `StatementTemplate`s.

**Comment by nikita-volkov** [comment]
> you have to specify those fields for each query currently, making it cumbersome to add new fields to the record.

Have you considered the "Examples of mapping to custom types" section of the [readme](https://github.com/nikita-volkov/hasql-th)? Seems like the `uncurryN` trick is what you need.

**Comment by domenkozar** [comment]
I'm using `uncurryN`, but I'm talking about column names (and bindings) that still need to be repeated.

**Comment by nikita-volkov** [comment]
Oh I think I see now. You're looking for ways of reusing parts of your queries. Have you tried the [`Snippet`](http://hackage.haskell.org/package/hasql-dynamic-statements-0.2.0.2/docs/Hasql-DynamicStatements-Snippet.html) abstraction?

**Comment by nikita-volkov** [comment]
Any way, I don't have any vision for the sort of "subtemplating" that you've suggested here nor do I see any terrible usefulness in it. So it wouldn't be wise for me to either develop nor maintain such functionality.

I welcome you to release it as your own package. You can even reuse the parser since I've now exposed it in the "postgresql-syntax" package and consult the "hasql-th" sources for examples of syntax tree analysis.

**Comment by domenkozar** [comment]
That's fair, thanks!
