### ISSUE TITLE
Not in scope "maybeStatement"

### ISSUE THREAD

**Issue by seymen** [nikita-volkov/hasql-th#18]
Hello

Newbie here, suffering from the following error:

```
 error:
    • Not in scope: ‘maybeStatement’
    • In the quasi-quotation:
        [maybeStatement|
    select name :: text, email :: text, phone :: text?
    from "user"
    where id = $1 :: int4
    |]
```

I have hasql queries running perfectly fine. I am trying with Hasql.TH extension now.

Here is what I have done so far:
* added `hasql-th` to `build-depends` in cabal.
* `import Hasql.TH` on the module itself
* It compiles fine up to here
* Pasted the example in the documentation
```
selectUserDetails :: Statement Int32 (Maybe (Text, Text, Maybe Text))
selectUserDetails =
  [maybeStatement|
... and the rest
```

And I am getting that `Not in scope: maybeStatement` error. I have a feeling that I am missing something simple here. 

Appreciate any pointers that you might have.

**Comment by nikita-volkov** [comment]
Do you have the quasi-quotes language extension enabled?

You can list it in the "default-extensions" section of your Cabal file to have it enabled across your project or to have it enabled locally in a file add the following before the module declaration:

```haskell
{-# LANGUAGE QuasiQuotes #-}
```

**Comment by seymen** [comment]
Yep, I got that but doesn't seem to help.

Here is the entire file:
```
{-# LANGUAGE QuasiQuotes #-}

module Main where

import           Data.Int
import           Data.Text
import           Hasql.Statement
import           Hasql.TH

selectUserDetails :: Statement Int32 (Maybe (Text, Text, Maybe Text))
selectUserDetails =
  [maybeStatement|
    select name :: text, email :: text, phone :: text?
    from "user"
    where id = $1 :: int4
    |]

main :: IO ()
main = putStrLn "Hello, Haskell!"
```

The error I am getting:
```
Main.hs:13:3: error:
    • Not in scope: ‘maybeStatement’
    • In the quasi-quotation:
        [maybeStatement|
    select name :: text, email :: text, phone :: text?
    from "user"
    where id = $1 :: int4
    |]
   |
13 |   [maybeStatement|
   |   ^^^^^^^^^^^^^^^^...
```

**Comment by seymen** [comment]
If I explicitly ask for `maybeStatement`:

```
import           Hasql.TH        (maybeStatement)
```

I am getting the following error:
```
Main.hs:8:35: error:
    Module ‘Hasql.TH’ does not export ‘maybeStatement’
  |
8 | import           Hasql.TH        (maybeStatement)
  |                                   ^^^^^^^^^^^^^^
```

I must be doing something silly.

**Comment by nikita-volkov** [comment]
Oh. I think I know the answer. You must have the older version installed. Just specify the bounds for a later version in Cabal.

BTW, it is in best practice to explicitly specify version ranges unless you're using Stack.

**Comment by seymen** [comment]
I see... Thanks a lot for looking into this for me - I assumed cabal was choosing the latest versions of packages by default.

I've tried to specify the version bounds for the latest hasql and hasql-th in cabal but unfortunately this results in an error in resolving the dependencies. Looking at the cabal error messages, it seems that the culprit is the fast-builder package which depends on an old version of base (>=4.8 && <4.14). The version of base that I am using is 4.14.

The dependency goes like this:
hasql-th --> postgresql-syntax --> fast-builder

As cabal cannot install fast-builder due to conflict with base, it fails to satisfy dependencies for postresql-syntax, which in turn results in failure to install the latest version of hasql-th.

```
❯ cabal build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: hasql-th-test-0.1.0.0 (user goal)
[__1] trying: postgresql-syntax-0.3.0.3 (dependency of hasql-th-test)
[__2] trying: fast-builder-0.1.2.0 (dependency of postgresql-syntax)
[__3] next goal: base (dependency of hasql-th-test)
[__3] rejecting: base-4.14.0.0/installed-4.14.0.0 (conflict: fast-builder =>
base>=4.8 && <4.14)
[__3] skipping: base-4.14.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.8 && <4.14' from
'fast-builder')
[__3] rejecting: base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0,
base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
```

**Comment by nikita-volkov** [comment]
I guess I'll have to move away from the dependency on "fast-builder", since [I've reported the base bounds issue in May](https://github.com/takano-akio/fast-builder/issues/12) and there has been no reaction to this day.

**Comment by seymen** [comment]
:+1: I've also put a comment in there. Hopefully that can be resolved soon.

Thanks a lot for all your help and assistance here. Much appreciated.

**Comment by seymen** [comment]
Great news - compilation is working now after the fix in fast-builder. 

Thanks again for your assistance.
