### ISSUE TITLE
Add package on Stackage

### ISSUE THREAD

**Issue by keuhdall** [nikita-volkov/hasql-th#19]
Hello,

Unlike hasql, this project doesn't seem to be released on stackage.
Is that on purpose or is a stackage release planned ?

**Comment by nikita-volkov** [comment]
You can add it to Stackage. Just PR to them.

**Comment by keuhdall** [comment]
Sure ! Is it ok to register myself as stackage maintainer though ?
Stackage guidelines states `It's highly encouraged that the actual package maintainer is also the Stackage maintainer`
I'd understand however if you don't have time, and I don't mind doing this myself if you don't have time for that.

**Comment by nikita-volkov** [comment]
Yes, I would prefer not becoming the maintainer. Too many things to maintain on my plate already :) Thanks!

**Comment by keuhdall** [comment]
I'll close this issue, unfortunately `hasql-th` depends on `postgresql-syntax`, which is not stackage either.
Since it's one your libs as well, I was okay being maintainer for this one as well, however it depends on other externals libs that are not on stackage either, and I don't feel like adding all these.
Thanks for your quick answers anyway !
