### ISSUE TITLE
Enable checked sql files

### ISSUE THREAD

**Issue by popara** [nikita-volkov/hasql-th#5]
Hi,

I have been using for some time `hasql` and I was excited to try out your new shiny thing. One thing that I am really missing is the ability to check sql files, because I have big complex queries that I would be happy to be able to check them at compile time.

I don't know how complex it may be, but I just wanted to give a suggestion from a perspective of 2-year user of your library (yes, I have been renaming stuff and adopting to your api  :) )

Thank you for awesome work 
<3

**Comment by nikita-volkov** [comment]
Thanks for your feedback.

Checking of SQL files would require broadening the scope of the parser from just the preparable statements to the whole syntax tree of Postgres. That's a lot of work, so I doubt it'll be done any time soon.

**Comment by popara** [comment]
Oh, sorry, obviously you know more than me :)

My idea was just to load file and treat it as is "simple" TH like `[maybeStatement|`. 

If you say that it requires more work than that let's just forget it :)

**Comment by charlescrain** [comment]
Yeah would be really cool if we could keep our _preparable statements_ in separate sql files. Definitely second this feature.

**Comment by csamak** [comment]
This might also make it easier to write a simple extension that checks the statements against a schema at test time (i.e. given db connection, check these sql files).

**Comment by nikita-volkov** [comment]
> Yeah would be really cool if we could keep our _preparable statements_ in separate sql files. Definitely second this feature.
> 
> P.S. Great work on this library!

Am I right in understanding that you want to store SQL of each statement in a separate file? Why do you need that?

**Comment by nikita-volkov** [comment]
> This might also make it easier to write a simple extension that checks the statements against a schema at test time (i.e. given db connection, check these sql files).

Why do you think you need to store statements in separate files for that? What's stopping you from testing the generated Hasql `Statement`?

**Comment by csamak** [comment]
> > This might also make it easier to write a simple extension that checks the statements against a schema at test time (i.e. given db connection, check these sql files).
> 
> Why do you think you need to store statements in separate files for that? What's stopping you from testing the generated Hasql `Statement`?

Nothing, so maybe my statement shouldn't be considered for this feature.

I was imagining putting complex queries in a directory structure and then easily checking them all in a simple test. Then I know they pass said test by their existence in that structure (as opposed to creating a list in the test, possibly missing some unless there's some logic that searches for `Statement`s in .hs code).

**Comment by popara** [comment]
> > Yeah would be really cool if we could keep our _preparable statements_ in separate sql files. Definitely second this feature.
> > P.S. Great work on this library!
> 
> Am I right in understanding that you want to store SQL of each statement in a separate file? Why do you need that?

I am having complex queries, that sometimes spawns 100s of lines, I like to have them in separate files, because of syntax highlighting and readability.

**Comment by nikita-volkov** [comment]
Since I've misunderstood the original premise of this issue and the discussion has spawned several separate subjects, the discussion in this thread has lost focus. To fix this I've isolated the subjects into dedicated issues. Please continue the discussion there or create other issues if you think I've left something uncovered. Closing this issue.

The original premise of this issue should be covered by #6.
